name: Auto-label staging-to-main PRs
# auto labels the staging-to-main PRs with version bump label
on:
  pull_request:
    types: [opened]
    branches: [main]

permissions:
  pull-requests: write
  issues: write

jobs:
  add-label:
    if: github.event.pull_request.head.ref == 'new-staging'
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      
      - name: Add version bump label
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          GH_REPO: ${{ github.repository}}

          PR: ${{ github.event.pull_request.number }}
        run:
          gh label create "version bump" \
            --repo "$GH_REPO" \
            --description "Bump version when this PR is merged" \
            --color "0E8A16" || true

          gh pr edit "$PR" --repo "$GH_REPO" --add-label "version bump"
